sudo: required

services:
  - docker

script:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - docker run -it $DOCKER_USERNAME/$DOCKER_REPO adl;
  - export ID=`docker ps -a -q`;
  - docker stop $ID;
  - docker commit $ID $DOCKER_USERNAME/$DOCKER_REPO;
  - docker push $DOCKER_USERNAME/$DOCKER_REPO;
